package task2.controller;

public enum CommandName {
	
	SING_IN, REGISTER, WRONG_REQUEST, ALL_CATEGORIES, ALL_EQUIPMENT_IN_CATEGORY, 
	SELECTED_EQUIPMENT, RENT_EQUIPMENT, SHOW_RENTED_EQUIPMENT, RETURN_EQUIPMENT;

}
